# spring.application.name=booking
# spring.datasource.url=jdbc:mysql://localhost:3306/booking
# spring.datasource.username=root
# spring.datasource.password=quan
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.web.error.include-stacktrace=never

# app.frontend.base-url=http://localhost:3000
# spring.servlet.multipart.max-file-size=50MB

# file.upload-base-path=uploads/images
# cloudinary.cloud-name=dvyi5jxrm
# cloudinary.api-key=279225335537268
# cloudinary.api-secret=2TO-TRjGAQ-RuzbeL6ODcdqkoTA

# file.storage-mode=cloudinary
# file.public-base-url=http://localhost:8080/storage
# # default = 10MB (form data)
# spring.servlet.multipart.max-request-size=50MB


# JWT_SECRET=my_super_secret_256_key111111111
# JWT_ACCESS_TOKEN_EXPIRATION=86400
# JWT_REFRESH_TOKEN_EXPIRATION=864000 
# VERIFICATION_TOKEN_EXPIRATION=300
# LOCK_TIME=9000
# MAX_FAILED_LOGIN=5



# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=nguyenvietquan.30032004@gmail.com
# spring.mail.password=tiqpythqhwxmctgx
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true




spring.application.name=booking

# ===== DATABASE =====
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.web.error.include-stacktrace=never

# ===== FRONTEND =====
app.frontend.base-url=${FRONTEND_BASE_URL}

# ===== FILE UPLOAD =====
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

file.upload-base-path=uploads/images
file.storage-mode=${FILE_STORAGE_MODE}
file.public-base-url=${FILE_PUBLIC_BASE_URL}

# ===== CLOUDINARY =====
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ===== JWT =====
JWT_SECRET=${JWT_SECRET}
JWT_ACCESS_TOKEN_EXPIRATION=${JWT_ACCESS_TOKEN_EXPIRATION}
JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION}

# ===== SECURITY =====
VERIFICATION_TOKEN_EXPIRATION=${VERIFICATION_TOKEN_EXPIRATION}
LOCK_TIME=${LOCK_TIME}
MAX_FAILED_LOGIN=${MAX_FAILED_LOGIN}

# ===== MAIL =====
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true