name: Deploy Spring Boot Production

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # ======================
  # BUILD JOB (CI)
  # ======================
  build:
    runs-on: ubuntu-latest

    environment: vps-hange

    steps:
      # checkout source code
      - name: Checkout source
        uses: actions/checkout@v4

      # setup Java 21
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # cấp quyền gradlew
      - name: Grant execute permission
        run: chmod +x gradlew

      # build Spring Boot bằng Gradle
      - name: Build with Gradle
        run: ./gradlew clean build -x test
